M48
; DRILL file {KiCad (6.0.4)} date Mon Jul 25 21:27:04 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-25T21:27:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C4.000
%
G90
G05
T1
X45.5Y-21.65
X45.5Y-28.65
T2
X28.75Y-23.825
X35.75Y-23.825
T3
X57.9Y-102.4
X89.2Y-102.4
T4
X118.0Y-86.5
T5
X33.0Y-91.0
T0
M30
